"use client";
import { useState, type FormEvent } from "react";
import { formatPeriod, type AgendaRecord, type AgendaKind, type AgendaInput } from "../../agenda/agenda-data";
import styles from "../eventos/eventos.module.css";
import agendaStyles from "../../agenda/agenda.module.css";
const blank=(kind:AgendaKind):AgendaInput=>({kind,title:"",startDate:"",endDate:"",description:"",published:true});
function Editor({kind,initial,loadError}:{kind:AgendaKind;initial:AgendaRecord[];loadError:string|null}) {
  const [items,setItems]=useState(initial); const [draft,setDraft]=useState(blank(kind)); const [editId,setEditId]=useState<number|null>(null); const [status,setStatus]=useState(loadError); const [busy,setBusy]=useState(false);
  const reservation=kind==="reservation";
  function field<K extends keyof AgendaInput>(key:K,value:AgendaInput[K]) { setDraft(d=>({...d,[key]:value})); }
  async function save(event:FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(null);
    try { const response=await fetch("/api/admin/agenda"+(editId?"/"+editId:""),{method:editId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}); const result=await response.json() as {item:AgendaRecord;error?:string}; if(!response.ok) throw new Error(result.error||"Não foi possível salvar."); setItems(old=>[...old.filter(i=>i.id!==result.item.id),result.item].sort((a,b)=>a.startDate.localeCompare(b.startDate))); setDraft(blank(kind)); setEditId(null); setStatus(reservation?"Reserva salva. As noites já aparecem em vermelho no site.":result.item.published?"Feriado publicado na área de sugestões.":"Feriado salvo como rascunho."); } catch(e) { setStatus(e instanceof Error?e.message:"Não foi possível salvar."); } finally { setBusy(false); }
  }
  async function remove(item:AgendaRecord) { if(!window.confirm(reservation?"Excluir esta reserva e liberar as noites no calendário?":"Excluir este feriado prolongado?")) return; setBusy(true);
    try { const response=await fetch("/api/admin/agenda/"+item.id,{method:"DELETE"}); const result=await response.json() as {error?:string}; if(!response.ok) throw new Error(result.error||"Não foi possível excluir."); setItems(old=>old.filter(i=>i.id!==item.id)); if(editId===item.id){setEditId(null);setDraft(blank(kind));} setStatus("Período excluído."); } catch(e){setStatus(e instanceof Error?e.message:"Não foi possível excluir.");} finally {setBusy(false);}
  }
  return <section aria-labelledby={kind+"-title"}><h2 className={agendaStyles.editorHeading} id={kind+"-title"}>{reservation?"Reservas da casa":"Feriados prolongados"}</h2><div className={styles.managerGrid}>
    <form className={styles.eventForm} onSubmit={save}><div className={styles.formHeading}><h3>{editId?"Editar período":reservation?"Cadastrar reserva":"Cadastrar feriado"}</h3></div>
      <label>{reservation?"Identificação interna da reserva":"Nome do feriado"}<input required maxLength={120} value={draft.title} onChange={e=>field("title",e.target.value)} placeholder={reservation?"Ex.: Reserva de outubro":"Ex.: Feriado de outubro"}/></label>
      {reservation&&<p className={styles.fieldHint}>Essa identificação e as observações não aparecem para os visitantes.</p>}
      <div className={styles.formRow}><label>{reservation?"Data de entrada":"Início do período"}<input required type="date" min="2000-01-01" max="2100-12-31" value={draft.startDate} onChange={e=>field("startDate",e.target.value)}/></label><label>{reservation?"Data de saída":"Fim do período"}<input required type="date" min={draft.startDate||"2000-01-01"} max="2100-12-31" value={draft.endDate} onChange={e=>field("endDate",e.target.value)}/></label></div>
      <p className={styles.fieldHint}>{reservation?"As noites entre a entrada e a saída ficam reservadas. O dia da saída fica livre para uma nova entrada.":"Inclua os dias de emenda sugeridos. O cadastro não bloqueia o calendário."}</p>
      <label>{reservation?"Observações internas (opcional)":"Descrição para o visitante (opcional)"}<textarea maxLength={500} rows={3} value={draft.description} onChange={e=>field("description",e.target.value)}/></label>
      {!reservation&&<label className={styles.publishToggle}><input type="checkbox" checked={draft.published} onChange={e=>field("published",e.target.checked)}/><span>Publicar para os visitantes<small>Desmarque para guardar como rascunho.</small></span></label>}
      {status&&<p className={styles.formStatus} role="status">{status}</p>}<button className={styles.primaryButton} disabled={busy||!!loadError}>{busy?"Salvando…":"Salvar período"}</button>{editId&&<button type="button" className={styles.cancelButton} disabled={busy} onClick={()=>{setEditId(null);setDraft(blank(kind));setStatus(null);}}>Cancelar edição</button>}
    </form>
    <div className={styles.eventList}><div className={styles.listHeading}><h3>{reservation?"Reservas cadastradas":"Feriados cadastrados"}</h3><span className={styles.counter}>{items.length}</span></div>{!items.length&&<p className={styles.emptyState}>{loadError||"Nenhum período cadastrado."}</p>}{items.map(item=><article key={item.id} className={styles.eventItem}><div className={styles.eventItemTop}><span className={item.published?styles.published:styles.draft}>{reservation?"Reservado":item.published?"Publicado":"Rascunho"}</span></div><h3>{item.title}</h3><p>{formatPeriod(item.startDate,item.endDate)}{reservation?" · entrada / saída":""}</p>{item.description&&<p style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{item.description}</p>}<div className={styles.itemActions}><button type="button" disabled={busy} onClick={()=>{setEditId(item.id);setDraft({...item});setStatus(null);}}>Editar</button><button type="button" disabled={busy} className={styles.deleteButton} onClick={()=>remove(item)}>Excluir</button></div></article>)}</div>
  </div></section>;
}
export default function AgendaManager({initial,loadError}:{initial:AgendaRecord[];loadError:string|null}) { return <div className={agendaStyles.editorSections}><Editor kind="reservation" initial={initial.filter(i=>i.kind==="reservation")} loadError={loadError}/><Editor kind="holiday" initial={initial.filter(i=>i.kind==="holiday")} loadError={loadError}/></div>; }
